title: Victor Journé
subtitle: Data Scientist
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://devlopr.netlify.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    #- text: Shop
    #  url : /shop/
    - text: About Me
      url: /about/
    - text: Contact Me
      url : /contact/
    #- text: Styleguide
    #  url: /styleguide/


# Edit theses details

author_logo: profile.png
#author: John Doe
author_bio: Welcome to my personal site! Please find some articles or projects that I would like to share!
#author_email: "journe.victor@gmail.com"
author_location: Paris

author_work_experiences:
            - company_name: French Ministry of Interior
              company_logo: mi.png
              company_url: https://www.interieur.gouv.fr/
              designation: Data Scientist (2019 - Now)
              description: Led multiple projects in Computer Vision, Natural Language processing and full stack development.
              visibility: true
            - company_name: Qopius Technology
              company_logo: qopius.jpeg
              company_url: https://qopius.com/
              designation: Data Scientist (2017 - 2019)
              description: Achieved applied researches in attention learning, graphs matching and deep-learning detection models.
              visibility: true
            - company_name: Engie
              company_logo: engie.png
              company_url: https://engie.com/
              designation: Quantitative Analyst (2015 - 2017)
              description: Found profitable strategies on the Imbalance and Intraday Power Market.
              visibility: true

author_education_details:
              - college_logo: ensae.png
                college_name: ENSAE
                college_url: https://www.ensae.fr/formation/masteres-specialises/data-science/
                college_degree: Master of Data Science (2016-2017)
                description: Optimization for Machine Learning, Online Learning, Hidden Markov Models, Compressed Sensing, Deep Learning.
                visibility: true
              - college_logo: cranfield.png
                college_name: Cranfield University (2014-2015)
                college_url: https://www.cranfield.ac.uk/courses/taught/autonomous-vehicle-dynamics-and-control
                college_degree: Master of Data Science
                description: Double diploma about autonomous vehicles. Control Theory, Dynamics, Decision-Making and Data Fusion.
                visibility: true
              - college_logo: ecn.png
                college_name: Ecole Centrale de Nantes (2013-2015)
                college_url: https://www.ec-nantes.fr/
                college_degree: Master of Science
                description: Mathematics (analysis, probabilities, optimization), Fluid Dynamics, Control and Automation and Signal Theory. Simulation and Virtual Reality.
                visibility: true

author_project_details:
              - project_thumbnail: logo-ridoc.png
                project_title: RIDOC
                project_description: A Search Engine for the French Mininstery of Interior
                project_url: http://ridoc.fr
                visibility: true
              - project_thumbnail: logo-ia-flash.png
                project_title: IA Flash
                project_description: A platform to find the brand/model of cars
                project_url: https://iaflash.fr
                visibility: true
              - project_thumbnail: Emoji.png
                project_title: Emotion classifier
                project_description: School project to classify facial emotion with CNN
                project_url: https://github.com/victorjourne/facial_emotion_CNN/blob/master/README.md
                visibility: true
              - project_thumbnail: logo-spark.png
                project_title:
                project_description: School project, Spark for the logistic regression
                project_url: https://github.com/victorjourne/logistic_regression_spark/blob/master/ELTDM_CodeSource_Lelievre_Journe_public.ipynb
                visibility: false

# social links
#twitter_username: johndoe
github_username:  victorjourne
#facebook_username: johndoe
linkedin_username: victorjourne
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments using disqus
disqus_shortname: sujay-kundu

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# formspree (contact form)
formspree_email: mpzblqkb

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
  - jemoji
# - jekyll-archives

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
